name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm 9
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check project can build successfully
        run: pnpm run build